import * as Icon from "../../../packages/icons/src";

export const list = [
    {
        title: "a",
        components: [
            {
                item: <Icon.AddressBook />,
                name: "address-book",
                tags: [
                    "contacts",
                    "directory",
                    "roledex",
                    "communications",
                    "address",
                    "book",
                ],
            },
            {
                item: <Icon.AirPlay />,
                name: "airplay",
                tags: [
                    "apple",
                    "screencasting",
                    "television",
                    "tv",
                    "media",
                    "system",
                    "airplay",
                ],
            },
            {
                item: <Icon.Alarm />,
                name: "alarm",
                tags: [
                    "times",
                    "timer",
                    "clock",
                    "schedule",
                    "events",
                    "watch",
                    "system",
                    "alarm",
                ],
            },
            {
                item: <Icon.AlignBottom />,
                name: "align-bottom",
                tags: [
                    "alignment",
                    "arrangement",
                    "layout",
                    "flush bottom",
                    "design",
                    "editor",
                    "align",
                    "bottom",
                ],
            },
            {
                item: <Icon.AlignCenterHorizontal />,
                name: "align-center-horizontal",
                tags: [
                    "alignment",
                    "arrangement",
                    "layout",
                    "centered",
                    "middle",
                    "design",
                    "editor",
                    "align",
                    "center",
                    "horizontal",
                ],
            },
            {
                item: <Icon.AlignCenterVertical />,
                name: "align-center-vertical",
                tags: [
                    "alignment",
                    "arrangement",
                    "layout",
                    "centered",
                    "middle",
                    "design",
                    "editor",
                    "align",
                    "center",
                    "vertical",
                ],
            },
            {
                item: <Icon.AlignLeft />,
                name: "align-left",
                tags: [
                    "alignment",
                    "arrangement",
                    "layout",
                    "flush left",
                    "design",
                    "editor",
                    "align",
                    "left",
                ],
            },
            {
                item: <Icon.AlignRight />,
                name: "align-right",
                tags: [
                    "alignment",
                    "arrangement",
                    "layout",
                    "flush right",
                    "design",
                    "editor",
                    "align",
                    "right",
                ],
            },
            {
                item: <Icon.AlignTop />,
                name: "align-top",
                tags: [
                    "alignment",
                    "arrangement",
                    "layout",
                    "flush top",
                    "design",
                    "editor",
                    "align",
                    "top",
                ],
            },
            {
                item: <Icon.AndroidLogo />,
                name: "android-logo",
                tags: [
                    "logos",
                    "google",
                    "mobile",
                    "phone",
                    "cellular",
                    "cellphone",
                    "brands",
                    "technology & development",
                    "system",
                    "android",
                    "logo",
                ],
            },
            {
                item: <Icon.AngularLogo />,
                name: "angular-logo",
                tags: [
                    "framework",
                    "javascript",
                    "google",
                    "web",
                    "brands",
                    "technology & development",
                    "angular",
                    "logo",
                ],
            },
            {
                item: <Icon.Aperture />,
                name: "aperture",
                tags: [
                    "photography",
                    "cameras",
                    "pictures",
                    "lens",
                    "design",
                    "media",
                    "aperture",
                ],
            },
            {
                item: <Icon.AppStoreLogo />,
                name: "app-store-logo",
                tags: [
                    "macintosh",
                    "imac",
                    "iphone",
                    "ipad",
                    "macos",
                    "ios",
                    "brands",
                    "app",
                    "store",
                    "logo",
                ],
            },
            {
                item: <Icon.AppWindow />,
                name: "app-window",
                tags: [
                    "windows",
                    "software",
                    "programs",
                    "applications",
                    "communications",
                    "system",
                    "app",
                    "window",
                ],
            },
            {
                item: <Icon.ApplePodcastsLogo />,
                name: "apple-podcasts-logo",
                tags: [
                    "macintosh",
                    "imac",
                    "iphone",
                    "ipad",
                    "macos",
                    "ios",
                    "brands",
                    "media",
                    "apple",
                    "podcasts",
                    "logo",
                ],
            },
            {
                item: <Icon.Archive />,
                name: "archive",
                tags: [
                    "saved",
                    "saving",
                    "archived",
                    "archiving",
                    "archival",
                    "downloaded",
                    "downloading",
                    "office",
                    "system",
                    "archive",
                ],
            },
            {
                item: <Icon.ArrowCounterClockwise />,
                name: "arrow-counter-clockwise",
                tags: [
                    "directional",
                    "pointer",
                    "pointing",
                    "arrowhead",
                    "undo",
                    "refreshing",
                    "rotate",
                    "spin",
                    "flip",
                    "arrows",
                    "arrow",
                    "counter",
                    "clockwise",
                ],
            },
            {
                item: <Icon.ArrowDown />,
                name: "arrow-down",
                tags: [
                    "directional",
                    "pointer",
                    "pointing",
                    "arrowhead",
                    "arrows",
                    "arrow",
                    "down",
                ],
            },
            {
                item: <Icon.ArrowLeft />,
                name: "arrow-left",
                tags: [
                    "directional",
                    "pointer",
                    "pointing",
                    "arrowhead",
                    "arrows",
                    "arrow",
                    "left",
                ],
            },
            {
                item: <Icon.ArrowLeftArc />,
                name: "arrow-arc-left",
                tags: [
                    "directional",
                    "pointer",
                    "pointing",
                    "arrowhead",
                    "arrows",
                    "arrow",
                    "arc",
                    "left",
                ],
            },
            {
                item: <Icon.ArrowLineLeft />,
                name: "arrow-line-left",
                tags: [
                    "directional",
                    "pointer",
                    "pointing",
                    "arrowhead",
                    "arrows",
                    "arrow",
                    "line",
                    "left",
                ],
            },
            {
                item: <Icon.ArrowLineRight />,
                name: "arrow-line-right",
                tags: [
                    "directional",
                    "pointer",
                    "pointing",
                    "arrowhead",
                    "arrows",
                    "arrow",
                    "line",
                    "right",
                ],
            },
            {
                item: <Icon.ArrowOutLineHorizontal />,
                name: "arrows-out-line-horizontal",
                tags: [
                    "directional",
                    "pointer",
                    "pointing",
                    "arrowhead",
                    "arrows",
                    "arrow",
                    "line",
                    "right",
                ],
            },
            {
                item: <Icon.ArrowRight />,
                name: "arrow-right",
                tags: [
                    "directional",
                    "pointer",
                    "pointing",
                    "arrowhead",
                    "arrows",
                    "arrow",
                    "right",
                ],
            },
            {
                item: <Icon.ArrowSquareIn />,
                name: "arrow-square-in",
                tags: [
                    "import",
                    "directional",
                    "pointer",
                    "pointing",
                    "arrowhead",
                    "arrows",
                    "arrow",
                    "square",
                    "in",
                ],
            },
            {
                item: <Icon.ArrowSquareOut />,
                name: "arrow-square-out",
                tags: [
                    "export",
                    "external",
                    "directional",
                    "pointer",
                    "pointing",
                    "arrowhead",
                    "arrows",
                    "arrow",
                    "square",
                    "out",
                ],
            },
            {
                item: <Icon.ArrowUp />,
                name: "arrow-up",
                tags: [
                    "directional",
                    "pointer",
                    "pointing",
                    "arrowhead",
                    "arrows",
                    "arrow",
                    "up",
                ],
            },
            {
                item: <Icon.ArrowsClockwise />,
                name: "arrows-clockwise",
                tags: [
                    "directional",
                    "pointer",
                    "pointing",
                    "arrowhead",
                    "redo",
                    "refreshing",
                    "sync",
                    "synchronize",
                    "rotate",
                    "spin",
                    "flip",
                    "arrows",
                    "clockwise",
                ],
            },
            {
                item: <Icon.ArrowsCounterClockwise />,
                name: "arrows-counter-clockwise",
                tags: [
                    "directional",
                    "pointer",
                    "pointing",
                    "arrowhead",
                    "undo",
                    "refreshing",
                    "rotate",
                    "spin",
                    "flip",
                    "arrows",
                    "counter",
                    "clockwise",
                ],
            },
            {
                item: <Icon.ArrowsDownUp />,
                name: "arrows-down-up",
                tags: [
                    "directional",
                    "pointer",
                    "pointing",
                    "arrowhead",
                    "arrows",
                    "down",
                    "up",
                ],
            },
            {
                item: <Icon.ArrowsIn />,
                name: "arrows-in",
                tags: [
                    "directional",
                    "pointer",
                    "pointing",
                    "arrowhead",
                    "collapse",
                    "minimize",
                    "resize",
                    "shrink",
                    "arrows",
                    "in",
                ],
            },
            {
                item: <Icon.ArrowsInLineHorizontal />,
                name: "arrows-in-line-horizontal",
                tags: [
                    "directional",
                    "pointer",
                    "pointing",
                    "arrowhead",
                    "close",
                    "center",
                    "align",
                    "arrows",
                    "design",
                    "editor",
                    "in",
                    "line",
                    "horizontal",
                ],
            },
            {
                item: <Icon.ArrowsInLineVertical />,
                name: "arrows-in-line-vertical",
                tags: [
                    "directional",
                    "pointer",
                    "pointing",
                    "arrowhead",
                    "close",
                    "center",
                    "align",
                    "arrows",
                    "design",
                    "editor",
                    "in",
                    "line",
                    "vertical",
                ],
            },
            {
                item: <Icon.ArrowsInSimple />,
                name: "arrows-in-simple",
                tags: [
                    "directional",
                    "pointer",
                    "pointing",
                    "arrowhead",
                    "collapse",
                    "minimize",
                    "resize",
                    "arrows",
                    "in",
                    "simple",
                ],
            },
            {
                item: <Icon.ArrowsLeftRight />,
                name: "arrows-left-right",
                tags: [
                    "directional",
                    "pointer",
                    "pointing",
                    "arrowhead",
                    "arrows",
                    "left",
                    "right",
                ],
            },
            {
                item: <Icon.ArrowsMerge />,
                name: "arrows-merge",
                tags: ["arrowheads", "join", "combine", "arrows", "merge"],
            },
            {
                item: <Icon.ArrowsOutCardinal />,
                name: "arrows-out-cardinal",
                tags: [
                    "directional",
                    "pointer",
                    "pointing",
                    "arrowhead",
                    "expand",
                    "fullscreen",
                    "resize",
                    "pan",
                    "move",
                    "grow",
                    "arrows",
                    "out",
                    "cardinal",
                ],
            },
            {
                item: <Icon.ArrowsOut />,
                name: "arrows-out",
                tags: [
                    "directional",
                    "pointer",
                    "pointing",
                    "arrowhead",
                    "expand",
                    "fullscreen",
                    "resize",
                    "grow",
                    "arrows",
                    "out",
                ],
            },
            {
                item: <Icon.ArrowsOutLineVertical />,
                name: "arrows-out-line-vertical",
                tags: [
                    "directional",
                    "pointer",
                    "pointing",
                    "arrowhead",
                    "open",
                    "split",
                    "arrows",
                    "design",
                    "editor",
                    "out",
                    "line",
                    "vertical",
                ],
            },
            {
                item: <Icon.ArrowsOutSimple />,
                name: "arrows-out-simple",
                tags: [
                    "directional",
                    "pointer",
                    "pointing",
                    "arrowhead",
                    "expand",
                    "fullscreen",
                    "resize",
                    "arrows",
                    "out",
                    "simple",
                ],
            },
            {
                item: <Icon.ArrowsSortDown />,
                name: "arrows-sort-down",
                tags: [
                    "directional",
                    "pointer",
                    "pointing",
                    "arrowhead",
                    "arrows",
                    "down",
                    "up",
                ],
            },
            {
                item: <Icon.ArrowsSortUp />,
                name: "arrows-sort-up",
                tags: [
                    "directional",
                    "pointer",
                    "pointing",
                    "arrowhead",
                    "arrows",
                    "down",
                    "up",
                ],
            },
            {
                item: <Icon.ArrowsSortUpDown />,
                name: "arrows-sort-up-down",
                tags: [
                    "directional",
                    "pointer",
                    "pointing",
                    "arrowhead",
                    "arrows",
                    "down",
                    "up",
                ],
            },
            {
                item: <Icon.Article />,
                name: "article",
                tags: [
                    "reading",
                    "writing",
                    "journals",
                    "periodicals",
                    "text",
                    "newspaper",
                    "media",
                    "objects",
                    "article",
                ],
            },
            {
                item: <Icon.At />,
                name: "at",
                tags: [
                    "@",
                    "address",
                    "email",
                    "at symbol",
                    "commercial at",
                    "arobase",
                    "communications",
                    "at",
                ],
            },
        ],
    },
    {
        title: "b",
        components: [
            {
                item: <Icon.Backspace />,
                name: "backspace",
                tags: ["keyboard", "remove", "delete", "system", "backspace"],
            },
            {
                item: <Icon.BalanceGeometry />,
                name: "balance-geometry",
                tags: [
                    "geometry",
                    "square",
                    "triangle",
                    "design",
                    "shapes",
                    "measure",
                    "balance",
                    "law",
                    "justice",
                    "government",
                    "commerce",
                    "maps & travel",
                    "objects",
                    "scales",
                ],
            },
            {
                item: <Icon.Bank />,
                name: "bank",
                tags: [
                    "banking",
                    "checking",
                    "money",
                    "savings",
                    "deposit",
                    "withdraw",
                    "places",
                    "locations",
                    "finances",
                    "maps & travel",
                    "bank",
                ],
            },
            {
                item: <Icon.Barcode />,
                name: "barcode",
                tags: [
                    "upc",
                    "qr",
                    "products",
                    "shopping",
                    "scanner",
                    "commerce",
                    "system",
                    "barcode",
                ],
            },
            {
                item: <Icon.BehanceLogo />,
                name: "behance-logo",
                tags: [
                    "logos",
                    "illustration",
                    "ui",
                    "interface",
                    "brands",
                    "design",
                    "behance",
                    "logo",
                ],
            },
            {
                item: <Icon.BellRinging />,
                name: "bell-ringing",
                tags: [
                    "alarm",
                    "notifications",
                    "times",
                    "timer",
                    "clock",
                    "schedule",
                    "events",
                    "ringer",
                    "calls",
                    "system",
                    "bell",
                    "ringing",
                ],
            },
            {
                item: <Icon.Bluetooth />,
                name: "bluetooth",
                tags: [
                    "wireless",
                    "connection",
                    "connected",
                    "connectivity",
                    "system",
                    "bluetooth",
                ],
            },
            {
                item: <Icon.Book />,
                name: "book",
                tags: [
                    "reading",
                    "reader",
                    "novel",
                    "story",
                    "library",
                    "office",
                    "media",
                    "objects",
                    "book",
                ],
            },
            {
                item: <Icon.BookmarkSimple />,
                name: "bookmark-simple",
                tags: [
                    "reading",
                    "reader",
                    "novel",
                    "story",
                    "placeholder",
                    "favorites",
                    "favorited",
                    "library",
                    "office",
                    "media",
                    "objects",
                    "bookmark",
                    "simple",
                ],
            },
            {
                item: <Icon.Bookmarks />,
                name: "bookmarks",
                tags: [
                    "reading",
                    "reader",
                    "novel",
                    "story",
                    "placeholder",
                    "favorites",
                    "favorited",
                    "library",
                    "office",
                    "objects",
                    "bookmarks",
                ],
            },
            {
                item: <Icon.BoundingBox />,
                name: "bounding-box",
                tags: [
                    "polygon",
                    "shapes",
                    "outline",
                    "corners",
                    "rectangle",
                    "design",
                    "bounding",
                    "box",
                ],
            },
            {
                item: <Icon.Briefcase />,
                name: "briefcase",
                tags: [
                    "suitcase",
                    "valise",
                    "baggage",
                    "folders",
                    "portfolio",
                    "office",
                    "objects",
                    "briefcase",
                ],
            },
            {
                item: <Icon.Broadcast />,
                name: "broadcast",
                tags: [
                    "radio",
                    "hotspot",
                    "wifi",
                    "emit",
                    "communications",
                    "media",
                    "system",
                    "broadcast",
                ],
            },
            {
                item: <Icon.BrowserGear />,
                name: "browser-gear",
                tags: [
                    "web browsers",
                    "windows",
                    "internet",
                    "website",
                    "webpage",
                    "chrome",
                    "edge",
                    "firefox",
                    "communications",
                    "system",
                    "browser",
                ],
            },
            {
                item: <Icon.Browsers />,
                name: "browsers",
                tags: [
                    "web browsers",
                    "windows",
                    "internet",
                    "website",
                    "webpage",
                    "chrome",
                    "edge",
                    "firefox",
                    "communications",
                    "system",
                    "browsers",
                ],
            },
            {
                item: <Icon.Bug />,
                name: "bug",
                tags: [
                    "debug",
                    "errors",
                    "insect",
                    "ladybug",
                    "technology & development",
                    "nature",
                    "bug",
                ],
            },
            {
                item: <Icon.BuildingOffice />,
                name: "building-office",
                tags: [
                    "places",
                    "locations",
                    "company",
                    "business",
                    "buildings",
                    "commerce",
                    "maps & travel",
                    "building",
                    "office",
                ],
            },
        ],
    },
    {
        title: "c",
        components: [
            {
                item: <Icon.Cake />,
                name: "cake",
                tags: [
                    "dessert",
                    "birthday",
                    "celebration",
                    "event",
                    "objects",
                    "cake",
                ],
            },
            {
                item: <Icon.Calculator />,
                name: "calculator",
                tags: [
                    "addition",
                    "sum",
                    "subtraction",
                    "difference",
                    "multiply",
                    "multiplication",
                    "product",
                    "divide",
                    "division",
                    "divisor",
                    "dividend",
                    "quotient",
                    "equals",
                    "equality",
                    "mathematics",
                    "arithmetic",
                    "+",
                    "-",
                    "±",
                    "×",
                    "÷",
                    "=",
                    "technology & development",
                    "finances",
                    "office",
                    "objects",
                    "calculator",
                ],
            },
            {
                item: <Icon.Calendar />,
                name: "calendar",
                tags: [
                    "dates",
                    "times",
                    "events",
                    "schedule",
                    "office",
                    "system",
                    "calendar",
                ],
            },
            {
                item: <Icon.Camera />,
                name: "camera",
                tags: [
                    "photography",
                    "pictures",
                    "lens",
                    "media",
                    "system",
                    "objects",
                    "camera",
                ],
            },
            {
                item: <Icon.CameraSlash />,
                name: "camera-slash",
                tags: [
                    "photography",
                    "pictures",
                    "lens",
                    "disabled",
                    "media",
                    "system",
                    "camera",
                    "slash",
                ],
            },
            {
                item: <Icon.CaretDoubleDown />,
                name: "caret-double-down",
                tags: [
                    "chevron",
                    "directional",
                    "pointer",
                    "pointing",
                    "arrowhead",
                    "triangle",
                    "arrows",
                    "caret",
                    "double",
                    "down",
                ],
            },
            {
                item: <Icon.CaretDoubleLeft />,
                name: "caret-double-left",
                tags: [
                    "chevron",
                    "directional",
                    "pointer",
                    "pointing",
                    "arrowhead",
                    "triangle",
                    "arrows",
                    "caret",
                    "double",
                    "left",
                ],
            },
            {
                item: <Icon.CaretDoubleRight />,
                name: "caret-double-right",
                tags: [
                    "chevron",
                    "directional",
                    "pointer",
                    "pointing",
                    "arrowhead",
                    "triangle",
                    "arrows",
                    "caret",
                    "double",
                    "right",
                ],
            },
            {
                item: <Icon.CaretDoubleUp />,
                name: "caret-double-up",
                tags: [
                    "chevron",
                    "directional",
                    "pointer",
                    "pointing",
                    "arrowhead",
                    "triangle",
                    "arrows",
                    "caret",
                    "double",
                    "up",
                ],
            },
            {
                item: <Icon.CaretDown />,
                name: "caret-down",
                tags: [
                    "chevron",
                    "directional",
                    "pointer",
                    "pointing",
                    "arrowhead",
                    "triangle",
                    "arrows",
                    "caret",
                    "down",
                ],
            },
            {
                item: <Icon.CaretLeft />,
                name: "caret-left",
                tags: [
                    "chevron",
                    "directional",
                    "pointer",
                    "pointing",
                    "arrowhead",
                    "triangle",
                    "arrows",
                    "caret",
                    "left",
                ],
            },
            {
                item: <Icon.CaretRight />,
                name: "caret-right",
                tags: [
                    "chevron",
                    "directional",
                    "pointer",
                    "pointing",
                    "arrowhead",
                    "triangle",
                    "arrows",
                    "caret",
                    "right",
                ],
            },
            {
                item: <Icon.CaretUp />,
                name: "caret-up",
                tags: [
                    "chevron",
                    "directional",
                    "pointer",
                    "pointing",
                    "arrowhead",
                    "triangle",
                    "arrows",
                    "caret",
                    "up",
                ],
            },
            {
                item: <Icon.ChartBar />,
                name: "chart-bar",
                tags: [
                    "graphs",
                    "graphing",
                    "charts",
                    "statistics",
                    "histogram",
                    "analyze",
                    "analysis",
                    "finances",
                    "office",
                    "chart",
                    "bar",
                ],
            },
            {
                item: <Icon.ChartBarHorizontal />,
                name: "chart-bar-horizontal",
                tags: [
                    "graphs",
                    "graphing",
                    "charts",
                    "statistics",
                    "histogram",
                    "analyze",
                    "analysis",
                    "finances",
                    "office",
                    "chart",
                    "bar",
                    "horizontal",
                ],
            },
            {
                item: <Icon.ChartLine />,
                name: "chart-line",
                tags: [
                    "graphs",
                    "graphing",
                    "charts",
                    "statistics",
                    "analyze",
                    "analysis",
                    "stocks",
                    "finances",
                    "office",
                    "chart",
                    "line",
                ],
            },
            {
                item: <Icon.ChartPieSlice />,
                name: "chart-pie-slice",
                tags: [
                    "graphs",
                    "graphing",
                    "charts",
                    "statistics",
                    "circle",
                    "analyze",
                    "analysis",
                    "finances",
                    "office",
                    "chart",
                    "pie",
                    "slice",
                ],
            },
            {
                item: <Icon.ChartPieSliceSimple />,
                name: "chart-pie-slice-simple",
                tags: [
                    "graphs",
                    "graphing",
                    "charts",
                    "statistics",
                    "circle",
                    "analyze",
                    "analysis",
                    "finances",
                    "office",
                    "chart",
                    "pie",
                    "slice",
                ],
            },
            {
                item: <Icon.ChatDots />,
                name: "chat-dots",
                tags: [
                    "send",
                    "sent",
                    "messages",
                    "messaging",
                    "sms",
                    "texting",
                    "comment",
                    "square",
                    "bubble",
                    "communications",
                    "chat",
                    "dots",
                ],
            },
            {
                item: <Icon.ChatQueue />,
                name: "chat-queue",
                tags: [
                    "send",
                    "sent",
                    "messages",
                    "messaging",
                    "sms",
                    "texting",
                    "comment",
                    "square",
                    "bubble",
                    "communications",
                    "chat",
                ],
            },
            {
                item: <Icon.Chats />,
                name: "chats",
                tags: [
                    "send",
                    "sent",
                    "messages",
                    "messaging",
                    "sms",
                    "texting",
                    "comment",
                    "square",
                    "bubble",
                    "communications",
                    "chats",
                ],
            },
            {
                item: <Icon.Check />,
                name: "check",
                tags: [
                    "todo",
                    "to-do",
                    "task",
                    "list",
                    "checkbox",
                    "ok",
                    "done",
                    "system",
                    "check",
                ],
            },
            {
                item: <Icon.CheckCircle />,
                name: "check-circle",
                tags: [
                    "todo",
                    "to-do",
                    "task",
                    "list",
                    "checkbox",
                    "round",
                    "ok",
                    "done",
                    "system",
                    "check",
                    "circle",
                ],
            },
            {
                item: <Icon.CheckSquare />,
                name: "check-square",
                tags: [
                    "todo",
                    "to-do",
                    "task",
                    "list",
                    "checkbox",
                    "rectangle",
                    "ok",
                    "done",
                    "system",
                    "check",
                    "square",
                ],
            },
            {
                item: <Icon.Checks />,
                name: "checks",
                tags: [
                    "todo",
                    "task",
                    "to-do",
                    "list",
                    "checkbox",
                    "ok",
                    "done",
                    "system",
                    "checks",
                ],
            },
            {
                item: <Icon.CirclesThreePlus />,
                name: "circles-three-plus",
                tags: [
                    "round",
                    "shapes",
                    "polygons",
                    "+",
                    "design",
                    "circles",
                    "three",
                    "plus",
                ],
            },
            {
                item: <Icon.Clipboard />,
                name: "clipboard",
                tags: [
                    "copy",
                    "copied",
                    "checklist",
                    "office",
                    "editor",
                    "system",
                    "clipboard",
                ],
            },
            {
                item: <Icon.ClipboardText />,
                name: "clipboard-text",
                tags: [
                    "copy",
                    "copied",
                    "checklist",
                    "office",
                    "editor",
                    "system",
                    "clipboard",
                    "text",
                ],
            },
            {
                item: <Icon.ClipboardTextSimple />,
                name: "clipboard-text-simple",
                tags: [
                    "copy",
                    "copied",
                    "checklist",
                    "office",
                    "editor",
                    "system",
                    "clipboard",
                    "text",
                ],
            },
            {
                item: <Icon.Clock />,
                name: "clock",
                tags: [
                    "times",
                    "timer",
                    "alarm",
                    "schedule",
                    "events",
                    "watch",
                    "system",
                    "objects",
                    "clock",
                ],
            },
            {
                item: <Icon.ClockClockwise />,
                name: "clock-clockwise",
                tags: [
                    "times",
                    "timer",
                    "alarm",
                    "schedule",
                    "events",
                    "restore",
                    "fast forward",
                    "update",
                    "system",
                    "clock",
                    "clockwise",
                ],
            },
            {
                item: <Icon.ClockCounterClockwise />,
                name: "clock-counter-clockwise",
                tags: [
                    "times",
                    "timer",
                    "alarm",
                    "schedule",
                    "events",
                    "restore",
                    "fast forward",
                    "update",
                    "system",
                    "clock",
                    "clockwise",
                    "counter",
                ],
            },
            {
                item: <Icon.Code />,
                name: "code",
                tags: [
                    "angle brackets",
                    "angle braces",
                    "snippets",
                    "technology & development",
                    "editor",
                    "code",
                ],
            },
            {
                item: <Icon.CodepenLogo />,
                name: "codepen-logo",
                tags: [
                    "ide",
                    "logos",
                    "brands",
                    "technology & development",
                    "codepen",
                    "logo",
                ],
            },
            {
                item: <Icon.CodesandboxLogo />,
                name: "codesandbox-logo",
                tags: [
                    "ide",
                    "logos",
                    "brands",
                    "technology & development",
                    "codesandbox",
                    "logo",
                ],
            },
            {
                item: <Icon.Coffee />,
                name: "coffee",
                tags: [
                    "tea",
                    "java",
                    "beverages",
                    "drinks",
                    "cafe",
                    "cup",
                    "mug",
                    "espresso",
                    "cappuccino",
                    "latte",
                    "places",
                    "locations",
                    "bars",
                    "restaurants",
                    "food",
                    "dining",
                    "commerce",
                    "objects",
                    "maps & travel",
                    "coffee",
                ],
            },
            {
                item: <Icon.Columns />,
                name: "columns",
                tags: [
                    "shapes",
                    "polygons",
                    "box",
                    "stack",
                    "list",
                    "table",
                    "cards",
                    "design",
                    "columns",
                ],
            },
            {
                item: <Icon.Contract />,
                name: "contract",
                tags: [
                    "purchase",
                    "money",
                    "clipping",
                    "expense",
                    "commerce",
                    "finances",
                    "receipt",
                ],
            },
            {
                item: <Icon.Copy />,
                name: "copy",
                tags: [
                    "duplicated",
                    "copied",
                    "clipboard",
                    "editor",
                    "system",
                    "copy",
                ],
            },
            {
                item: <Icon.CopyRight />,
                name: "copyright",
                tags: [
                    "©",
                    "intellectual property",
                    "copr.",
                    "symbol",
                    "commerce",
                    "media",
                    "copyright",
                ],
            },
            {
                item: <Icon.CopySimple />,
                name: "copy-simple",
                tags: [
                    "duplicated",
                    "copied",
                    "clipboard",
                    "editor",
                    "system",
                    "copy",
                    "simple",
                ],
            },
            {
                item: <Icon.CornersIn />,
                name: "corners-in",
                tags: [
                    "collapse",
                    "windowed",
                    "minimized",
                    "system",
                    "corners",
                    "in",
                ],
            },
            {
                item: <Icon.CornersOut />,
                name: "corners-out",
                tags: [
                    "expand",
                    "fullscreen",
                    "maximized",
                    "system",
                    "corners",
                    "out",
                ],
            },
            {
                item: <Icon.Cpu />,
                name: "cpu",
                tags: [
                    "processor",
                    "microchip",
                    "computer",
                    "circuit",
                    "technology & development",
                    "cpu",
                ],
            },
            {
                item: <Icon.CreditCard />,
                name: "credit-card",
                tags: [
                    "debit",
                    "visa",
                    "mastercard",
                    "money",
                    "payment",
                    "paying",
                    "purchase",
                    "swipe",
                    "commerce",
                    "finances",
                    "credit",
                    "card",
                ],
            },
            {
                item: <Icon.Crop />,
                name: "crop",
                tags: [
                    "photography",
                    "clip",
                    "screenshots",
                    "design",
                    "editor",
                    "crop",
                ],
            },
            {
                item: <Icon.Crown />,
                name: "crown",
                tags: [
                    "king",
                    "queen",
                    "royalty",
                    "monarch",
                    "ruler",
                    "leader",
                    "chess",
                    "games",
                    "objects",
                    "crown",
                ],
            },
            {
                item: <Icon.Cube />,
                name: "cube",
                tags: [
                    "square",
                    "box",
                    "3d",
                    "volume",
                    "blocks",
                    "design",
                    "games",
                    "objects",
                    "cube",
                ],
            },
            {
                item: <Icon.CurrencyCircleDollar />,
                name: "currency-circle-dollar",
                tags: [
                    "money",
                    "usd",
                    "payment",
                    "paying",
                    "purchase",
                    "commerce",
                    "finances",
                    "currency",
                    "circle",
                    "dollar",
                ],
            },
            {
                item: <Icon.CurrencyDollar />,
                name: "currency-dollar",
                tags: [
                    "money",
                    "usd",
                    "payment",
                    "paying",
                    "purchase",
                    "commerce",
                    "finances",
                    "currency",
                    "dollar",
                ],
            },
            {
                item: <Icon.CurrencyEur />,
                name: "currency-eur",
                tags: [
                    "money",
                    "euros",
                    "payment",
                    "paying",
                    "purchase",
                    "commerce",
                    "finances",
                    "currency",
                    "eur",
                ],
            },
            {
                item: <Icon.CurrencyGbp />,
                name: "currency-gbp",
                tags: [
                    "money",
                    "pounds sterling",
                    "payment",
                    "paying",
                    "purchase",
                    "commerce",
                    "finances",
                    "currency",
                    "gbp",
                ],
            },
            {
                item: <Icon.CurrencyInr />,
                name: "currency-inr",
                tags: [
                    "money",
                    "rupees",
                    "payment",
                    "paying",
                    "purchase",
                    "commerce",
                    "finances",
                    "currency",
                    "inr",
                ],
            },
            {
                item: <Icon.Cursor />,
                name: "cursor",
                tags: [
                    "pointer",
                    "arrowhead",
                    "mouse",
                    "click",
                    "design",
                    "system",
                    "cursor",
                ],
            },
            {
                item: <Icon.CursorText />,
                name: "cursor-text",
                tags: [
                    "i-beam",
                    "input",
                    "select",
                    "editor",
                    "system",
                    "cursor",
                    "text",
                ],
            },
        ],
    },
    {
        title: "d",
        components: [
            {
                item: <Icon.DashBoard />,
                name: "dashboard",
                tags: [
                    "apps",
                    "applications",
                    "squares",
                    "tiles",
                    "cells",
                    "tables",
                    "tabular",
                    "spreadsheets",
                    "excel",
                    "design",
                    "system",
                    "grid",
                    "four",
                ],
            },
            {
                item: <Icon.Database />,
                name: "database",
                tags: [
                    "saved",
                    "saving",
                    "archived",
                    "archiving",
                    "archival",
                    "hard disk",
                    "storage",
                    "hdd",
                    "servers",
                    "databases",
                    "technology & development",
                    "system",
                    "database",
                ],
            },
            {
                item: <Icon.Desktop />,
                name: "desktop",
                tags: [
                    "computer",
                    "pc",
                    "imac",
                    "tower",
                    "technology & development",
                    "objects",
                    "desktop",
                ],
            },
            {
                item: <Icon.DesktopTower />,
                name: "desktop-tower",
                tags: [
                    "computer",
                    "pc",
                    "imac",
                    "tower",
                    "technology & development",
                    "objects",
                    "desktop",
                ],
            },
            {
                item: <Icon.DeviceMobile />,
                name: "device-mobile",
                tags: ["cellphone", "cellular", "objects", "device", "mobile"],
            },
            {
                item: <Icon.Divide />,
                name: "divide",
                tags: [
                    "division",
                    "divisor",
                    "dividend",
                    "quotient",
                    "mathematics",
                    "arithmetic",
                    "calculator",
                    "technology & development",
                    "finances",
                    "divide",
                ],
            },
            {
                item: <Icon.DotsNine />,
                name: "dots-nine",
                tags: [
                    "grid",
                    "circles",
                    "shapes",
                    "polygons",
                    "design",
                    "dots",
                    "nine",
                ],
            },
            {
                item: <Icon.DotsSixVertical />,
                name: "dots-six-vertical",
                tags: [
                    "drag handle",
                    "knurling",
                    "circles",
                    "shapes",
                    "polygons",
                    "system",
                    "dots",
                    "six",
                    "vertical",
                ],
            },
            {
                item: <Icon.DotsThree />,
                name: "dots-three",
                tags: [
                    "menu",
                    "overflow",
                    "circles",
                    "shapes",
                    "polygons",
                    "ellipsis",
                    "ellipses",
                    "more",
                    "system",
                    "dots",
                    "three",
                ],
            },
            {
                item: <Icon.DotsThreeVertical />,
                name: "dots-three-vertical",
                tags: [
                    "menu",
                    "overflow",
                    "circles",
                    "shapes",
                    "polygons",
                    "ellipsis",
                    "ellipses",
                    "more",
                    "system",
                    "dots",
                    "three",
                    "vertical",
                ],
            },
            {
                item: <Icon.DownloadSimple />,
                name: "download-simple",
                tags: [
                    "saved",
                    "saving",
                    "archived",
                    "archiving",
                    "archival",
                    "downloaded",
                    "downloading",
                    "hard drive",
                    "disk",
                    "import",
                    "system",
                    "download",
                    "simple",
                ],
            },
            {
                item: <Icon.DribbbleLogo />,
                name: "dribbble-logo",
                tags: [
                    "logos",
                    "round",
                    "basketball",
                    "sports",
                    "design",
                    "brands",
                    "dribbble",
                    "logo",
                ],
            },
        ],
    },
    {
        title: "e",
        components: [
            {
                item: <Icon.Envelope />,
                name: "envelope",
                tags: [
                    "mail",
                    "email",
                    "send",
                    "sent",
                    "message",
                    "post",
                    "letter",
                    "communications",
                    "envelope",
                ],
            },
            {
                item: <Icon.EnvelopeOpen />,
                name: "envelope-open",
                tags: [
                    "mail",
                    "email",
                    "send",
                    "sent",
                    "message",
                    "read",
                    "post",
                    "letter",
                    "communications",
                    "envelope",
                    "open",
                ],
            },
            {
                item: <Icon.Equals />,
                name: "equals",
                tags: [
                    "equality",
                    "equivalent",
                    "equivalence",
                    "mathematics",
                    "arithmetic",
                    "calculator",
                    "technology & development",
                    "finances",
                    "equals",
                ],
            },
            {
                item: <Icon.Eraser />,
                name: "eraser",
                tags: [
                    "write",
                    "writing",
                    "editing",
                    "undo",
                    "deleted",
                    "design",
                    "editor",
                    "eraser",
                ],
            },
            {
                item: <Icon.Export />,
                name: "export",
                tags: [
                    "share",
                    "send to",
                    "arrows",
                    "communications",
                    "system",
                    "export",
                ],
            },
            {
                item: <Icon.Eye />,
                name: "eye",
                tags: [
                    "visible",
                    "hidden",
                    "show",
                    "hide",
                    "visibility",
                    "view",
                    "design",
                    "editor",
                    "eye",
                ],
            },
            {
                item: <Icon.EyeClock />,
                name: "eye-clock",
                tags: [
                    "visible",
                    "hidden",
                    "show",
                    "hide",
                    "visibility",
                    "view",
                    "design",
                    "editor",
                    "eye",
                    "times",
                    "timer",
                    "alarm",
                    "schedule",
                    "events",
                    "watch",
                    "system",
                    "objects",
                    "clock",
                ],
            },
            {
                item: <Icon.Eyedropper />,
                name: "eyedropper",
                tags: [
                    "colors",
                    "color picker",
                    "sample",
                    "arts",
                    "design",
                    "editor",
                    "objects",
                    "eyedropper",
                ],
            },
        ],
    },
] as const;
