import * as Icon from "../../../packages/icons/src";

export const list = [
    {
        title: "a",
        components: [
            {
                item: <Icon.AddressBook />,
                name: "address-book",
                tags: [
                    "contacts",
                    "directory",
                    "roledex",
                    "communications",
                    "address",
                    "book",
                ],
            },
            {
                item: <Icon.AirPlay />,
                name: "airplay",
                tags: [
                    "apple",
                    "screencasting",
                    "television",
                    "tv",
                    "media",
                    "system",
                    "airplay",
                ],
            },
            {
                item: <Icon.Alarm />,
                name: "alarm",
                tags: [
                    "times",
                    "timer",
                    "clock",
                    "schedule",
                    "events",
                    "watch",
                    "system",
                    "alarm",
                ],
            },
            {
                item: <Icon.AlignBottom />,
                name: "align-bottom",
                tags: [
                    "alignment",
                    "arrangement",
                    "layout",
                    "flush bottom",
                    "design",
                    "editor",
                    "align",
                    "bottom",
                ],
            },
            {
                item: <Icon.AlignCenterHorizontal />,
                name: "align-center-horizontal",
                tags: [
                    "alignment",
                    "arrangement",
                    "layout",
                    "centered",
                    "middle",
                    "design",
                    "editor",
                    "align",
                    "center",
                    "horizontal",
                ],
            },
            {
                item: <Icon.AlignCenterVertical />,
                name: "align-center-vertical",
                tags: [
                    "alignment",
                    "arrangement",
                    "layout",
                    "centered",
                    "middle",
                    "design",
                    "editor",
                    "align",
                    "center",
                    "vertical",
                ],
            },
            {
                item: <Icon.AlignLeft />,
                name: "align-left",
                tags: [
                    "alignment",
                    "arrangement",
                    "layout",
                    "flush left",
                    "design",
                    "editor",
                    "align",
                    "left",
                ],
            },
            {
                item: <Icon.AlignRight />,
                name: "align-right",
                tags: [
                    "alignment",
                    "arrangement",
                    "layout",
                    "flush right",
                    "design",
                    "editor",
                    "align",
                    "right",
                ],
            },
            {
                item: <Icon.AlignTop />,
                name: "align-top",
                tags: [
                    "alignment",
                    "arrangement",
                    "layout",
                    "flush top",
                    "design",
                    "editor",
                    "align",
                    "top",
                ],
            },
            {
                item: <Icon.AndroidLogo />,
                name: "android-logo",
                tags: [
                    "logos",
                    "google",
                    "mobile",
                    "phone",
                    "cellular",
                    "cellphone",
                    "brands",
                    "technology & development",
                    "system",
                    "android",
                    "logo",
                ],
            },
            {
                item: <Icon.AngularLogo />,
                name: "angular-logo",
                tags: [
                    "framework",
                    "javascript",
                    "google",
                    "web",
                    "brands",
                    "technology & development",
                    "angular",
                    "logo",
                ],
            },
            {
                item: <Icon.Aperture />,
                name: "aperture",
                tags: [
                    "photography",
                    "cameras",
                    "pictures",
                    "lens",
                    "design",
                    "media",
                    "aperture",
                ],
            },
            {
                item: <Icon.AppStoreLogo />,
                name: "app-store-logo",
                tags: [
                    "macintosh",
                    "imac",
                    "iphone",
                    "ipad",
                    "macos",
                    "ios",
                    "brands",
                    "app",
                    "store",
                    "logo",
                ],
            },
            {
                item: <Icon.AppWindow />,
                name: "app-window",
                tags: [
                    "windows",
                    "software",
                    "programs",
                    "applications",
                    "communications",
                    "system",
                    "app",
                    "window",
                ],
            },
            {
                item: <Icon.ApplePodcastsLogo />,
                name: "apple-podcasts-logo",
                tags: [
                    "macintosh",
                    "imac",
                    "iphone",
                    "ipad",
                    "macos",
                    "ios",
                    "brands",
                    "media",
                    "apple",
                    "podcasts",
                    "logo",
                ],
            },
            {
                item: <Icon.Archive />,
                name: "archive",
                tags: [
                    "saved",
                    "saving",
                    "archived",
                    "archiving",
                    "archival",
                    "downloaded",
                    "downloading",
                    "office",
                    "system",
                    "archive",
                ],
            },
            {
                item: <Icon.ArrowCounterClockwise />,
                name: "arrow-counter-clockwise",
                tags: [
                    "directional",
                    "pointer",
                    "pointing",
                    "arrowhead",
                    "undo",
                    "refreshing",
                    "rotate",
                    "spin",
                    "flip",
                    "arrows",
                    "arrow",
                    "counter",
                    "clockwise",
                ],
            },
            {
                item: <Icon.ArrowDown />,
                name: "arrow-down",
                tags: [
                    "directional",
                    "pointer",
                    "pointing",
                    "arrowhead",
                    "arrows",
                    "arrow",
                    "down",
                ],
            },
            {
                item: <Icon.ArrowLeft />,
                name: "arrow-left",
                tags: [
                    "directional",
                    "pointer",
                    "pointing",
                    "arrowhead",
                    "arrows",
                    "arrow",
                    "left",
                ],
            },
            {
                item: <Icon.ArrowLeftArc />,
                name: "arrow-arc-left",
                tags: [
                    "directional",
                    "pointer",
                    "pointing",
                    "arrowhead",
                    "arrows",
                    "arrow",
                    "arc",
                    "left",
                ],
            },
            {
                item: <Icon.ArrowLineLeft />,
                name: "arrow-line-left",
                tags: [
                    "directional",
                    "pointer",
                    "pointing",
                    "arrowhead",
                    "arrows",
                    "arrow",
                    "line",
                    "left",
                ],
            },
            {
                item: <Icon.ArrowLineRight />,
                name: "arrow-line-right",
                tags: [
                    "directional",
                    "pointer",
                    "pointing",
                    "arrowhead",
                    "arrows",
                    "arrow",
                    "line",
                    "right",
                ],
            },
            {
                item: <Icon.ArrowOutLineHorizontal />,
                name: "arrows-out-line-horizontal",
                tags: [
                    "directional",
                    "pointer",
                    "pointing",
                    "arrowhead",
                    "arrows",
                    "arrow",
                    "line",
                    "right",
                ],
            },
            {
                item: <Icon.ArrowRight />,
                name: "arrow-right",
                tags: [
                    "directional",
                    "pointer",
                    "pointing",
                    "arrowhead",
                    "arrows",
                    "arrow",
                    "right",
                ],
            },
            {
                item: <Icon.ArrowSquareIn />,
                name: "arrow-square-in",
                tags: [
                    "import",
                    "directional",
                    "pointer",
                    "pointing",
                    "arrowhead",
                    "arrows",
                    "arrow",
                    "square",
                    "in",
                ],
            },
            {
                item: <Icon.ArrowSquareOut />,
                name: "arrow-square-out",
                tags: [
                    "export",
                    "external",
                    "directional",
                    "pointer",
                    "pointing",
                    "arrowhead",
                    "arrows",
                    "arrow",
                    "square",
                    "out",
                ],
            },
            {
                item: <Icon.ArrowUp />,
                name: "arrow-up",
                tags: [
                    "directional",
                    "pointer",
                    "pointing",
                    "arrowhead",
                    "arrows",
                    "arrow",
                    "up",
                ],
            },
            {
                item: <Icon.ArrowsClockwise />,
                name: "arrows-clockwise",
                tags: [
                    "directional",
                    "pointer",
                    "pointing",
                    "arrowhead",
                    "redo",
                    "refreshing",
                    "sync",
                    "synchronize",
                    "rotate",
                    "spin",
                    "flip",
                    "arrows",
                    "clockwise",
                ],
            },
            {
                item: <Icon.ArrowsCounterClockwise />,
                name: "arrows-counter-clockwise",
                tags: [
                    "directional",
                    "pointer",
                    "pointing",
                    "arrowhead",
                    "undo",
                    "refreshing",
                    "rotate",
                    "spin",
                    "flip",
                    "arrows",
                    "counter",
                    "clockwise",
                ],
            },
            {
                item: <Icon.ArrowsDownUp />,
                name: "arrows-down-up",
                tags: [
                    "directional",
                    "pointer",
                    "pointing",
                    "arrowhead",
                    "arrows",
                    "down",
                    "up",
                ],
            },
            {
                item: <Icon.ArrowsIn />,
                name: "arrows-in",
                tags: [
                    "directional",
                    "pointer",
                    "pointing",
                    "arrowhead",
                    "collapse",
                    "minimize",
                    "resize",
                    "shrink",
                    "arrows",
                    "in",
                ],
            },
            {
                item: <Icon.ArrowsInLineHorizontal />,
                name: "arrows-in-line-horizontal",
                tags: [
                    "directional",
                    "pointer",
                    "pointing",
                    "arrowhead",
                    "close",
                    "center",
                    "align",
                    "arrows",
                    "design",
                    "editor",
                    "in",
                    "line",
                    "horizontal",
                ],
            },
            {
                item: <Icon.ArrowsInLineVertical />,
                name: "arrows-in-line-vertical",
                tags: [
                    "directional",
                    "pointer",
                    "pointing",
                    "arrowhead",
                    "close",
                    "center",
                    "align",
                    "arrows",
                    "design",
                    "editor",
                    "in",
                    "line",
                    "vertical",
                ],
            },
            {
                item: <Icon.ArrowsInSimple />,
                name: "arrows-in-simple",
                tags: [
                    "directional",
                    "pointer",
                    "pointing",
                    "arrowhead",
                    "collapse",
                    "minimize",
                    "resize",
                    "arrows",
                    "in",
                    "simple",
                ],
            },
            {
                item: <Icon.ArrowsLeftRight />,
                name: "arrows-left-right",
                tags: [
                    "directional",
                    "pointer",
                    "pointing",
                    "arrowhead",
                    "arrows",
                    "left",
                    "right",
                ],
            },
            {
                item: <Icon.ArrowsMerge />,
                name: "arrows-merge",
                tags: ["arrowheads", "join", "combine", "arrows", "merge"],
            },
            {
                item: <Icon.ArrowsOutCardinal />,
                name: "arrows-out-cardinal",
                tags: [
                    "directional",
                    "pointer",
                    "pointing",
                    "arrowhead",
                    "expand",
                    "fullscreen",
                    "resize",
                    "pan",
                    "move",
                    "grow",
                    "arrows",
                    "out",
                    "cardinal",
                ],
            },
            {
                item: <Icon.ArrowsOut />,
                name: "arrows-out",
                tags: [
                    "directional",
                    "pointer",
                    "pointing",
                    "arrowhead",
                    "expand",
                    "fullscreen",
                    "resize",
                    "grow",
                    "arrows",
                    "out",
                ],
            },
            {
                item: <Icon.ArrowsOutLineVertical />,
                name: "arrows-out-line-vertical",
                tags: [
                    "directional",
                    "pointer",
                    "pointing",
                    "arrowhead",
                    "open",
                    "split",
                    "arrows",
                    "design",
                    "editor",
                    "out",
                    "line",
                    "vertical",
                ],
            },
            {
                item: <Icon.ArrowsOutSimple />,
                name: "arrows-out-simple",
                tags: [
                    "directional",
                    "pointer",
                    "pointing",
                    "arrowhead",
                    "expand",
                    "fullscreen",
                    "resize",
                    "arrows",
                    "out",
                    "simple",
                ],
            },
            {
                item: <Icon.ArrowsSortDown />,
                name: "arrows-sort-down",
                tags: [
                    "directional",
                    "pointer",
                    "pointing",
                    "arrowhead",
                    "arrows",
                    "down",
                    "up",
                ],
            },
            {
                item: <Icon.ArrowsSortUp />,
                name: "arrows-sort-up",
                tags: [
                    "directional",
                    "pointer",
                    "pointing",
                    "arrowhead",
                    "arrows",
                    "down",
                    "up",
                ],
            },
            {
                item: <Icon.ArrowsSortUpDown />,
                name: "arrows-sort-up-down",
                tags: [
                    "directional",
                    "pointer",
                    "pointing",
                    "arrowhead",
                    "arrows",
                    "down",
                    "up",
                ],
            },
            {
                item: <Icon.Article />,
                name: "article",
                tags: [
                    "reading",
                    "writing",
                    "journals",
                    "periodicals",
                    "text",
                    "newspaper",
                    "media",
                    "objects",
                    "article",
                ],
            },
            {
                item: <Icon.At />,
                name: "at",
                tags: [
                    "@",
                    "address",
                    "email",
                    "at symbol",
                    "commercial at",
                    "arobase",
                    "communications",
                    "at",
                ],
            },
        ],
    },
] as const;
